# Generated by Django 4.2.3 on 2023-12-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('discription', models.TextField()),
                ('pro_img', models.FileField(upload_to='')),
            ],
        ),
    ]
